export const products = [
    {
        id: 1,
        img: "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=600",
        title: "Dr. Ahmed Farouk",
        price: 300,
        description: "Physics Professor specializing in quantum mechanics",
        category: "Online",
        subject: "Physics",
        rate: 2,
    },
    {
        id: 2,
        img: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=600",
        title: "Ms. Mona Khaled",
        price: 280,
        description: "Chemistry Instructor with focus on organic chemistry",
        category: "Offline",
        subject: "Chemistry",
        rate: 2,
    },
    {
        id: 3,
        img: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=600",
        title: "Prof. Youssef Ibrahim",
        price: 310,
        description: "Biology Lecturer specialized in genetics and microbiology",
        category: "Online",
        subject: "Biology",
        rate: 1,
    },
    {
        id: 4,
        img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600",
        title: "Ms. Sara Hany",
        price: 270,
        description: "High school Physics Teacher (Mechanics & Electricity)",
        category: "Offline",
        subject: "Physics",
        rate: 4,
    },
    {
        id: 7,
        img: "https://images.unsplash.com/photo-1557862921-37829c790f19?w=600",
        title: "Prof. Tamer Khalil",
        price: 310,
        description: "Physics Teacher with a passion for problem-solving",
        category: "Online",
        subject: "Geology",
        rate: 3,
    },
    {
        id: 10,
        img: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=600",
        title: "Ms. Dina Fathy",
        price: 280,
        description: "Chemistry Teacher with focus on SAT and IGCSE prep",
        category: "Offline",
        subject: "Physics",
        rate: 1,
    },
    {
        id: 11,
        img: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=600",
        title: "Eng. Ihab Saber",
        price: 300,
        description: "Applied Physics Instructor for engineering students",
        category: "Online",
        subject: "Physics",
        rate: 5,
    },
    {
        id: 12,
        img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600",
        title: "Dr. Mai Samir",
        price: 310,
        description: "Expert in Analytical Chemistry and Lab Experiments",
        category: "Offline",
        subject: "Physics",
        rate: 4,
    },
    {
        id: 14,
        img: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=600",
        title: "Ms. Rehab Salah",
        price: 270,
        description: "High school Chemistry teacher, Physical Chemistry focus",
        category: "Offline",
        subject: "Chemistry",
        rate: 5,
    },
    {
        id: 15,
        img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600",
        title: "Dr. Adham Ezzat",
        price: 320,
        description: "Professor of Molecular Biology and Genetics",
        category: "Online",
        subject: "Economics",
        rate: 5,
    },
    {
        id: 16,
        img: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600",
        title: "Ms. Nada Mohamed",
        price: 290,
        description: "Instructor for Physics and Environmental Science",
        category: "Offline",
        subject: "Political Science",
        rate: 4,
    },
    {
        id: 17,
        img: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=600",
        title: "Dr. Laila Hussein",
        price: 300,
        description: "Lecturer in Applied Chemistry and Biochemistry",
        category: "Online",
        subject: "Physics",
        rate: 5,
    },
    {
        id: 18,
        img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600",
        title: "Prof. Khaled Younis",
        price: 310,
        description: "Biology Instructor with expertise in Zoology",
        category: "Offline",
        subject: "Psychology",
        rate: 3,
    },
    {
        id: 19,
        img: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=600",
        title: "Ms. Mariam Shawky",
        price: 270,
        description: "Biology Teacher specializing in Human Anatomy",
        category: "Online",
        subject: "Physics",
        rate: 1,
    },
    {
        id: 20,
        img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600",
        title: "Prof. Hany Lotfy",
        price: 320,
        description: "Professor of Physics (Nuclear & Particle Physics)",
        category: "Offline",
        subject: "Chemistry",
        rate: 3,
    },
    {
        id: 21,
        img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600",
        title: "Ms. Nora Adel",
        price: 280,
        description: "High school Biology Teacher (IGCSE & IB)",
        category: "Online",
        subject: "Physics",
        rate: 3,
    },
    {
        id: 23,
        img: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=600",
        title: "Prof. Walid Magdy",
        price: 330,
        description: "Physics and Computer Science Instructor",
        category: "Online",
        subject: "Organic Chemistry",
        rate: 2,
    },
    {
        id: 24,
        img: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=600",
        title: "Ms. Farida Essam",
        price: 290,
        description: "Chemistry Teacher with interactive teaching style",
        category: "Offline",
        subject: "Inorganic Chemistry",
        rate: 2,
    },
    {
        id: 25,
        img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600",
        title: "Eng. Kareem Tarek",
        price: 310,
        description: "Applied Physics for engineering and sciences",
        category: "Online",
        subject: "Analytical Chemistry",
        rate: 2,
    },
    {
        id: 26,
        img: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=600",
        title: "Ms. Safa Emad",
        price: 270,
        description: "Instructor focusing on Biochemistry and Genetics",
        category: "Offline",
        subject: "Thermodynamics",
        rate: 5,
    },
    {
        id: 28,
        img: "https://images.unsplash.com/photo-1554151228-14d9def656e4?w=600",
        title: "Prof. Youssef Kamal",
        price: 300,
        description: "Lecturer in Earth Science and Geology",
        category: "Offline",
        subject: "Physics",
        rate: 3,
    },
    {
        id: 29,
        img: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600",
        title: "Dr. Salma Fawzy",
        price: 310,
        description: "Biology Professor, Cell Biology and Ecology Specialist",
        category: "Online",
        subject: "Mechanical Engineering",
        rate: 1,
    },
    {
        id: 30,
        img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600",
        title: "Ms. Nada Ibrahim",
        price: 280,
        description: "Science Teacher with focus on SAT/ACT prep",
        category: "Offline",
        subject: "Electrical Engineering",
        rate: 3,
    },
];

export const dataOfBanner = [
    {
        id: 1,
        title: "Learn Programming from Scratch",
        description: "Start your coding journey and master the basics of JavaScript, HTML, and CSS to build your first website.",
        image: "public/assets/Banner1.jpg",
    },
    {
        id: 2,
        title: "Boost Your Design Skills",
        description: "Discover the secrets of UI/UX design with Figma and Photoshop and create professional interfaces.",
        image: "public/assets/Banner2.jpg",
    },
    {
        id: 3,
        title: "Master Databases",
        description: "Learn how to build and manage SQL and NoSQL databases step by step with real projects.",
        image: "public/assets/Banner3.jpg",
    },
    {
        id: 4,
        title: "Business & Management Courses",
        description: "Learn the fundamentals of management, digital marketing, and project management to grow your career.",
        image: "./assets/Banner4.png",
    },
];

export const students = [
    {
        id: 1,
        name: "Ahmed Ali",
        age: 23,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600", // graduate portrait
        graduatetionYears: 2025,
        certificate: "Physics",
    },
    {
        id: 2,
        name: "Mohamed Adel",
        age: 22,
        graduatetionFrom: "Ain Shams University",
        img: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=600",
        graduatetionYears: 2024,
        certificate: "Chemistry",
    },
    {
        id: 3,
        name: "Omar Khaled",
        age: 24,
        graduatetionFrom: "Alexandria University",
        img: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=600",
        graduatetionYears: 2023,
        certificate: "Biology",
    },
    {
        id: 4,
        name: "Mona Hassan",
        age: 23,
        graduatetionFrom: "Mansoura University",
        img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600",
        graduatetionYears: 2022,
        certificate: "Science",
    },
    {
        id: 7,
        name: "Mohamed Samir",
        age: 24,
        graduatetionFrom: "Tanta University",
        img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600",
        graduatetionYears: 2021,
        certificate: "Biology",
    },
    {
        id: 8,
        name: "Aya Mostafa",
        age: 23,
        graduatetionFrom: "Zagazig University",
        img: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=600",
        graduatetionYears: 2024,
        certificate: "Science",
    },
    {
        id: 9,
        name: "Khaled Nasser",
        age: 25,
        graduatetionFrom: "Assiut University",
        img: "https://images.unsplash.com/photo-1524503033411-c9566986fc8f?w=600",
        graduatetionYears: 2023,
        certificate: "Physics",
    },
    {
        id: 10,
        name: "Heba Fathy",
        age: 22,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600",
        graduatetionYears: 2025,
        certificate: "Chemistry",
    },
    {
        id: 11,
        name: "Mostafa Mahmoud",
        age: 23,
        graduatetionFrom: "Ain Shams University",
        img: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=600",
        graduatetionYears: 2022,
        certificate: "Biology",
    },
    {
        id: 12,
        name: "Nourhan Saad",
        age: 21,
        graduatetionFrom: "Alexandria University",
        img: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=600",
        graduatetionYears: 2023,
        certificate: "Science",
    },
    {
        id: 13,
        name: "Mahmoud Adel",
        age: 24,
        graduatetionFrom: "Mansoura University",
        img: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600",
        graduatetionYears: 2025,
        certificate: "Physics",
    },
    {
        id: 15,
        name: "Ola Tarek",
        age: 22,
        graduatetionFrom: "Helwan University",
        img: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=600",
        graduatetionYears: 2024,
        certificate: "Biology",
    },
    {
        id: 16,
        name: "Ibrahim Salem",
        age: 25,
        graduatetionFrom: "Suez Canal University",
        img: "https://images.unsplash.com/photo-1546456073-6712f79251bb?w=600",
        graduatetionYears: 2025,
        certificate: "Science",
    },
    {
        id: 17,
        name: "Hossam Ali",
        age: 23,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600",
        graduatetionYears: 2023,
        certificate: "Physics",
    },
    {
        id: 18,
        name: "Yara Mahmoud",
        age: 22,
        graduatetionFrom: "Alexandria University",
        img: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=600",
        graduatetionYears: 2024,
        certificate: "Chemistry",
    },
    {
        id: 19,
        name: "Tamer Farid",
        age: 24,
        graduatetionFrom: "Ain Shams University",
        img: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=600",
        graduatetionYears: 2022,
        certificate: "Biology",
    },
    {
        id: 20,
        name: "Hager Saeed",
        age: 21,
        graduatetionFrom: "Mansoura University",
        img: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600",
        graduatetionYears: 2023,
        certificate: "Science",
    },
    {
        id: 21,
        name: "Samah Ali",
        age: 22,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600",
        graduatetionYears: 2024,
        certificate: "Physics",
    },
    {
        id: 24,
        name: "Amr Nabil",
        age: 24,
        graduatetionFrom: "Ain Shams University",
        img: "https://images.unsplash.com/photo-1546456073-6712f79251bb?w=600",
        graduatetionYears: 2025,
        certificate: "Science",
    },
    {
        id: 25,
        name: "Dina Adel",
        age: 22,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600",
        graduatetionYears: 2021,
        certificate: "Physics",
    },
    {
        id: 26,
        name: "Youssef Tarek",
        age: 23,
        graduatetionFrom: "Alexandria University",
        img: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=600",
        graduatetionYears: 2022,
        certificate: "Chemistry",
    },
    {
        id: 27,
        name: "Aya Hossam",
        age: 21,
        graduatetionFrom: "Zagazig University",
        img: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=600",
        graduatetionYears: 2023,
        certificate: "Biology",
    },
    {
        id: 28,
        name: "Mostafa Ali",
        age: 24,
        graduatetionFrom: "Assiut University",
        img: "https://images.unsplash.com/photo-1524503033411-c9566986fc8f?w=600",
        graduatetionYears: 2024,
        certificate: "Science",
    },
    {
        id: 29,
        name: "Sara Mahmoud",
        age: 23,
        graduatetionFrom: "Mansoura University",
        img: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=600",
        graduatetionYears: 2025,
        certificate: "Physics",
    },
    {
        id: 30,
        name: "Omar Fathy",
        age: 22,
        graduatetionFrom: "Helwan University",
        img: "https://images.unsplash.com/photo-1524503033411-c9566986fc8f?w=600",
        graduatetionYears: 2023,
        certificate: "Chemistry",
    },
    {
        id: 31,
        name: "Nour El-Din",
        age: 25,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600",
        graduatetionYears: 2022,
        certificate: "Biology",
    },
    {
        id: 32,
        name: "Hanaa Saeed",
        age: 23,
        graduatetionFrom: "Ain Shams University",
        img: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=600",
        graduatetionYears: 2021,
        certificate: "Science",
    },
    {
        id: 33,
        name: "Adel Mohamed",
        age: 24,
        graduatetionFrom: "Alexandria University",
        img: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600",
        graduatetionYears: 2025,
        certificate: "Physics",
    },
    {
        id: 34,
        name: "Nada Khaled",
        age: 21,
        graduatetionFrom: "Mansoura University",
        img: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=600",
        graduatetionYears: 2023,
        certificate: "Chemistry",
    },
    {
        id: 35,
        name: "Mahmoud Salem",
        age: 22,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=600",
        graduatetionYears: 2024,
        certificate: "Biology",
    },
    {
        id: 36,
        name: "Reem Samir",
        age: 23,
        graduatetionFrom: "Suez Canal University",
        img: "https://images.unsplash.com/photo-1546456073-6712f79251bb?w=600",
        graduatetionYears: 2022,
        certificate: "Science",
    },
    {
        id: 38,
        name: "Hadeer Mostafa",
        age: 22,
        graduatetionFrom: "Cairo University",
        img: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=600",
        graduatetionYears: 2023,
        certificate: "Chemistry",
    },
    {
        id: 39,
        name: "Khalifa Omar",
        age: 24,
        graduatetionFrom: "Ain Shams University",
        img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600",
        graduatetionYears: 2024,
        certificate: "Biology",
    },
];
